const { z } = require('zod');

const getDefaultGroupSettings = (chatId, title = 'Group') => ({
  chatId: String(chatId),
  title,
  language: 'en',
  isActive: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  media: {
    photo: true,
    video: true,
    audio: true,
    voice: true,
    document: true,
    sticker: true,
    animation: true,
    contact: false,
    location: false,
    venue: false,
    poll: true,
    dice: true,
  },
  regulation: {
    enabled: false,
    rules: '1. No spamming or flooding\n2. Be respectful to all members\n3. No offensive or adult content\n4. Follow admin instructions',
  },
  antispam: {
    enabled: true,
    threshold: 5,
    window: 10,
    action: 'delete',
    checkDuplicate: true,
    checkUrlSpam: true,
    checkMentionSpam: true,
  },
  antiflood: {
    enabled: true,
    threshold: 5,
    window: 10,
    action: 'mute',
  },
  welcome: {
    enabled: true,
    message: '👋 Welcome {mention} to {group}!\nPlease read and follow the group rules.',
    deleteAfter: 0,
  },
  goodbye: {
    enabled: false,
    message: '👋 Goodbye {user}!',
    deleteAfter: 60,
  },
  alphabets: {
    enabled: false,
    allowedScripts: ['LATIN'],
    action: 'delete',
  },
  captcha: {
    enabled: false,
    type: 'button',
    timeout: 120,
    action: 'kick',
  },
  checks: {
    enabled: false,
    blockBots: true,
    requireUsername: false,
    action: 'kick',
  },
  adminMention: {
    enabled: true,
    cooldown: 60,
    alertInGroup: true,
  },
  porn: {
    enabled: false,
    mode: 'disabled',
    action: 'delete',
  },
  warns: {
    enabled: true,
    maxWarns: 3,
    action: 'mute',
    muteDuration: 86400,
  },
  night: {
    enabled: false,
    start: '23:00',
    end: '06:00',
    timezone: 'Asia/Jakarta',
    action: 'delete',
    adminBypass: true,
  },
  tag: {
    enabled: true,
    allowTagAdmins: true,
    cooldown: 120,
  },
  link: {
    enabled: true,
    allowTelegramLinks: false,
    whitelistedDomains: ['youtube.com', 'youtu.be', 'github.com', 'google.com'],
    action: 'delete',
  },
  guardian: {
    enabled: true,
    threshold: 10,
    window: 10,
    duration: 600,
    action: 'kick',
  },
  approval: {
    enabled: false,
    autoApprove: false,
    notifyAdmins: true,
  },
  deletingMessages: {
    enabled: true,
    deleteJoin: true,
    deleteLeave: true,
    deleteCommands: true,
    deleteBot: false,
    timer: 30,
  },
});

const DatabaseSchema = z.object({
  groups: z.record(z.any()).default({}),
  users: z.record(z.any()).default({}),
  settings: z.record(z.any()).default({}),
  media: z.record(z.any()).default({}),
  regulation: z.record(z.any()).default({}),
  antispam: z.record(z.any()).default({}),
  antiflood: z.record(z.any()).default({}),
  welcome: z.record(z.any()).default({}),
  goodbye: z.record(z.any()).default({}),
  alphabets: z.record(z.any()).default({}),
  captcha: z.record(z.any()).default({}),
  checks: z.record(z.any()).default({}),
  adminMention: z.record(z.any()).default({}),
  blocks: z.array(z.any()).default([]),
  porn: z.record(z.any()).default({}),
  warnings: z.array(z.any()).default([]),
  warningHistory: z.array(z.any()).default([]),
  night: z.record(z.any()).default({}),
  tags: z.record(z.any()).default({}),
  links: z.record(z.any()).default({}),
  guardian: z.record(z.any()).default({}),
  approval: z.record(z.any()).default({}),
  deletingMessages: z.record(z.any()).default({}),
  languages: z.record(z.any()).default({}),
  customCommands: z.record(z.any()).default({}),
  statistics: z.record(z.any()).default({}),
  logs: z.array(z.any()).default([]),
});

const getEmptyDatabase = () => ({
  groups: {},
  users: {},
  settings: {},
  media: {},
  regulation: {},
  antispam: {},
  antiflood: {},
  welcome: {},
  goodbye: {},
  alphabets: {},
  captcha: {},
  checks: {},
  adminMention: {},
  blocks: [],
  porn: {},
  warnings: [],
  warningHistory: [],
  night: {},
  tags: {},
  links: {},
  guardian: {},
  approval: {},
  deletingMessages: {},
  languages: {},
  customCommands: {},
  statistics: {},
  logs: [],
});

module.exports = {
  getDefaultGroupSettings,
  DatabaseSchema,
  getEmptyDatabase,
};
